### ISSUE TITLE
Invalid Message From Server.

### ISSUE THREAD

**Issue by TunayAdaKaracan** [farisc0de/Uploady#12]
I just installed uploady but i can't upload any files. I will leave the website here: https://paste.kutuptilkisi.dev
How can i solve it?
*Note: I configured config.php properly and i already have an admin account which means db is working fine

**Comment by farisc0de** [comment]
Please provide a screenshot of the issue as the website is not accessable.

**Comment by emics** [comment]
the site is online
https://paste.kutuptilkisi.dev/

**Comment by TunayAdaKaracan** [comment]
Hello, i had to change my dnses to cloudflare. Thats why it was not accessible. It should be running now, but here is a picture in case it doesn't:
https://ibb.co/mzvLdmX

**Comment by emics** [comment]
strange things, i've upload two files right now.

**Comment by farisc0de** [comment]
Please change the env from production to development in config/enviromnet.php so I can be able to see any error logs generated by the upload api.

**Comment by TunayAdaKaracan** [comment]
Changes are made and published.

**Comment by farisc0de** [comment]
Please check with your hosting provider to enable this PHP extension `fileinfo` as it is required so this function works `mime_content_type()`.
