### ISSUE TITLE
An error when installing

### ISSUE THREAD

**Issue by sam1e-dev** [farisc0de/Uploady#15]
Hello! I ran the docker commands like said in the setup, but when i open my domain /install.php fill out the details and click Install, i get this error:

Fatal error: Uncaught Error: Call to a member function prepare() on null in /var/www/html/src/Uploady/Database.php:121 Stack trace: #0 /var/www/html/vendor/farisc0de/phpmigration/src/Migration.php(77): Uploady\Database->prepare('CREATE TABLE IF...') #1 /var/www/html/logic/installLogic.php(189): Farisc0de\PhpMigration\Migration->createTable('users', Array) #2 /var/www/html/install.php(3): include_once('/var/www/html/l...') #3 {main} thrown in /var/www/html/src/Uploady/Database.php on line 121

Anything i should do?
I kinda suck with code haha

**Comment by farisc0de** [comment]
did you update the config file with the database connection string?
