### ISSUE TITLE
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'api_key' at row 1

### ISSUE THREAD

**Issue by Flagelmann** [farisc0de/Uploady#20]
Hello,

I'm having the error in subject while trying installing Uploady.

The install.php is showing the following:

PHP Version: 8.2.15
JSON: Installed
PDO: Installed
MySQL: Installed
Mbstring: Installed
uploads: Writable
config/config.php: Writable
config/environment.php: Writable

Everything on the system is ok, also created and granted a SQL user to the empty DB created for this application, but now just getting the error:

SQLSTATE[01000]: Warning: 1265 Data truncated for column 'api_key' at row 1

**Comment by sicenul** [comment]
- Confirmed, it also happened to me.
- btw, I build the docker image and execute the docker compose

![image](https://github.com/farisc0de/Uploady/assets/64000634/93cf6b19-bda5-464a-bbbe-64950d2cc1f9)

**Comment by farisc0de** [comment]
I'll look into it.
