### ISSUE TITLE
White blank PHP page

### ISSUE THREAD

**Issue by bonnebulle** [farisc0de/Uploady#26]
Hello
This project looks greate
But when I follow instructions for a Rasbian local installation...
http://up.bonnebulle.xyz/install.php
I have a white no error page

I already do :
```chmod 755 -R uploady```

Php upgrade 
=> last v8 default + reboot
http://up.bonnebulle.xyz/phpinfo.php

config/config.php
```
<?php

// Database Settings
define("DB_HOST", "localhost");
define("DB_USER", "user_is_here");
define("DB_PASS", "password_is_here");
define("DB_NAME", "uploady");

// Application Settings
define("SITE_URL", "http://up.bonnebulle.xyz");
.  .  .
```

Mysql 
```CREATE DATABASE uploady```
```CREATE USER 'user_is_here'@'localhost' IDENTIFIED BY 'password_is_here;```

Nginx
```
server {
   server_name up.bonnebulle.xyz;
   index index.php;
   root /path/uploady/;

    location ~ \.php$ {
        try_files      $uri =404;
        fastcgi_index  index.php;
        fastcgi_pass   unix:/run/php/php8.0-fpm.sock;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }
}
```

Maybe you can help me
I will retry tomorrow (following yt video)
Thanks

**Comment by farisc0de** [comment]
If you are using a local installation I recommend deploying through Docker.

**Comment by bonnebulle** [comment]
Yes, Docker is easier way
but am using ARMhf 
(v7, non 64bit Raspberry)
Docker images build is ARM64
Thanks
