### ISSUE TITLE
Problems and missing features with installation and upload.

### ISSUE THREAD

**Issue by ozgurceozturkce** [farisc0de/Uploady#3]
Hello, first of all, I would like to thank you for your efforts for this beautiful project work.
Let me get right to the point;

First of all, while creating a new table as I mentioned below on line 194 of [../logic/installLogic.php](https://github.com/farisc0de/Uploady/blob/main/uploady/logic/installLogic.php#L194) during the installation process, the table name is defined as <mark>&nbsp;role&nbsp;</mark>.

```php
$install->createTable("role", $role);
```

However, again on line 373 of [../logic/installLogic.php](https://github.com/farisc0de/Uploady/blob/main/uploady/logic/installLogic.php#L373) (and a few more lines) it is defined as <mark>&nbsp;roles&nbsp;</mark> as in the example I added below.

```php
$install->insertValue("roles", [
            'id' => 2,
            'role' => 'User',
            'size_limit' => '150 MB',
        ]);
```
These differences cause the initial installation to fail.

Another problem is related to the <mark>&nbsp;downloads&nbsp;</mark> field, which is in the <mark>&nbsp;files&nbsp;</mark> table on line 58 of [../src/Uploady/Handler/UploadHandler.php](https://github.com/farisc0de/Uploady/blob/main/uploady/src/Uploady/Handler/UploadHandler.php#L58) but is not specified here.

The problem in this area is when uploading. Since the field does not have a default value when the table is first created, executing the code at line 64 after this code section results in an error that the file has no default value while saving it to the database. The file is uploaded but not saved in the database.

These are the problems I see so far. I hope I explained it in a proper and understandable English and it was useful for you.

I will not be able to use your project because it does not have the feature of specifying the file sharing period and the automatic deletion of the file at the end of this period, but I liked it. Built with a simple, beautiful configuration. Editing is easy.

Finally, thank you again for your work. Good luck.

Hello, first of all, I would like to thank you for your efforts for this beautiful project work.
Let me get right to the point;

First of all, while creating a new table as I mentioned below on line 194 of [../logic/installLogic.php](https://github.com/farisc0de/Uploady/blob/main/uploady/logic/installLogic.php#L194) during the installation process, the table name is defined as <mark>&nbsp;role&nbsp;</mark>.

```php
$install->createTable("role", $role);
```

However, again on line 373 of [../logic/installLogic.php](https://github.com/farisc0de/Uploady/blob/main/uploady/logic/installLogic.php#L373) (and a few more lines) it is defined as <mark>&nbsp;roles&nbsp;</mark> as in the example I added below.

```php
$install->insertValue("roles", [
            'id' => 2,
            'role' => 'User',
            'size_limit' => '150 MB',
        ]);
```
These differences cause the initial installation to fail.

Another problem is related to the <mark>&nbsp;downloads&nbsp;</mark> field, which is in the <mark>&nbsp;files&nbsp;</mark> table on line 58 of [../src/Uploady/Handler/UploadHandler.php](https://github.com/farisc0de/Uploady/blob/main/uploady/src/Uploady/Handler/UploadHandler.php#L58) but is not specified here.

The problem in this area is when uploading. Since the field does not have a default value when the table is first created, executing the code at line 64 after this code section results in an error that the file has no default value while saving it to the database. The file is uploaded but not saved in the database.

These are the problems I see so far. I hope I explained it in a proper and understandable English and it was useful for you.

I will not be able to use your project because it does not have the feature of specifying the file sharing period and the automatic deletion of the file at the end of this period, but I liked it. Built with a simple, beautiful configuration. Editing is easy.

Finally, thank you again for your work. Good luck.

**Comment by farisc0de** [comment]
I am so sorry for the typo and thank you for pointing it out, I'll fix it right away.

**Comment by ozgurceozturkce** [comment]
We're all human, we make mistakes. I also do it very often. The important thing is to fix it. Thank you for your understanding and quick response.

**Comment by farisc0de** [comment]
And the feature you specified is interesting, and I will add it to the development plan.
