### ISSUE TITLE
Multiple primary key defined

### ISSUE THREAD

**Issue by mzch** [farisc0de/Uploady#6]
When installing Uploady, the following error happens:

<img width="1462" alt="ScreenShot" src="https://github.com/farisc0de/Uploady/assets/621178/f4fb0676-aaec-4ab3-874a-4019d91f54b8">

OS: Debian `12,0`
PHP: `8.2.7`
MariaDB: `11.1`

**Comment by farisc0de** [comment]
Please, try it now after you drop the database, it should work.

**Comment by mzch** [comment]
Fine! Thanks! :)
