### ISSUE TITLE
Public uploads should be configurable

### ISSUE THREAD

**Issue by sicenul** [farisc0de/Uploady#9]
To avoid miss-used of the application by non responsible person, We need to force user to register before uploading. So it is very useful if there is a configurable setting in admin page to enable/disable public uploads.

**Comment by farisc0de** [comment]
Nice idea I'll put it in the backlog.

**Comment by emics** [comment]
> To avoid miss-used of the application by non responsible person, We need to force user to register before uploading. So it is very useful if there is a configurable setting in admin page to enable/disable public uploads.

Hi for workaround you can add this lines to the top of the file: **signup.php**
```
<?php
/// Lock Signup page
header("Location: login.php");
die();
/// 
```

and lock the SignUP function for new users. 
bye

**Comment by farisc0de** [comment]
[v3.0.6](https://github.com/farisc0de/Uploady/releases/tag/v3.0.6)
